library(DescTools)
library(ggplot2)
library(facetscales)
library(dplyr)
library(stringr)


###### DESCRIPTION

# Produces a panel made of a set of stacked boxplots (one for each distinct value of k), for each AF.
# Each boxplot reports the distribution of the proportion of true positives, cumulatively by length,
# by considering values generated by the Alternative models, with increasing gamma,
# with respect to the Null model.

# The output is a set of PNG images with name <AFMeasure>-Allk.png, where <AFMeasure> 
# stands for the actual value of AF measure being considered


# Note: this script must be executed after RawDistances-CSV2RDS

###### OPTIONS

# Sets the path of the directory containing either the sequences under analysis or the input dataframe

setwd("~/Universita/Src/IdeaProjects/power_statistics/data/results/dataset5-1000/jaccard")

# Sets the name of the file containing the input dataframe

###### CODE


################# functions 


# for labels
len_names <- list(
  '2e+05' = "n = 200 000",
  '1e+06' = "n = 1 000 000",
  '5e+06' = "n = 5 000 000",
  '6e+06' = "n = 6 000 000",
  '1e+07' = "n = 10 000 000")

k_names <- list(
  '4' = "k = 4",
  '5' = "k = 4",
  '6' = "k = 6",
  '8' = "k = 8",
  '10' = "k = 10",
  '11' = "k = 10")

# rename in a human readable format the measure names
measure_names <- function( measure) {
    ris <- str_to_title( switch( measure,
                 'chisquare' = 'chi square',
                 'd2star' = 'd2*',
                 'harmonicmean' = 'harmonic mean',
                 'squaredchord' = 'squared chord',
                 'jensenshannon' = 'jensen shannon',
                 'jaccard' = 'jaccard',
                 measure))
  return( ris)
}


plot_labeller <- function(variable,value){
  # cat(sprintf("variable: <%s>, value: <%s>\n", variable, as.character(value)))
  if (variable == 'len') {
    # N.B. len e' un factor
    return(len_names[as.character(value)])
  } else if (variable == 'k') {
    return(k_names[as.character(value)])
  } else if (variable == 'AM + k') {
    return(k_names[as.character(value)])
  } else {
    return(as.character(value))
  }
}

# modifica i fattori di scala per ciascuna riga del pannello
scales_y <- list(
#  `4` = scale_y_continuous(limits = c(1000000, 2000000), breaks = seq(0, 0.10, 0.02)),
  `4` = scale_y_continuous(limits = c(2320000, 2380000)),
  `10` = scale_y_continuous(limits = c(2320000, 2700000)))


ReadResults <- function( model, kVal, lenVal, g)
{
  ris <- data.frame( Distance = double(), Measure = character(), Model = character(), k = numeric(), len = numeric(),
                      A = numeric(), B = numeric(), C = numeric(), D = numeric(), N = numeric(), N.D.A = numeric(), stringsAsFactors=TRUE)
  
  gVal <- if (g != 0) sprintf(".G=%.3f", g) else ""
  mdl <- switch(model,
                "MotifRepl-U" = {paste0("MR", gVal)},
                "PatTransf-U" = { paste0("PT", gVal)},
                "Uniform" = { 'NM'},
                "Uniform-T1" = { 'T1'},
                stop("Wrong model value")
  ) 
  # name of the CSV file with distances for all measures
  #		model = 'Uniform' -> dist-k=8_Uniform-1000.1000000-values.csv
  #		model = 'PatTransf-U' -> dist-k=8_PatTransf-U-1000.6000000.G=0.050-values.csv
  f1 <- sprintf("k=%d/dist-k=%d_%s-%d.%d%s-values.csv", kVal, kVal, model, nPairs, lenVal, gVal)
  
  if (!file.exists(f1)) {
    cat(sprintf("Input csv: %s not found ... skipping.", f1))
    return(NULL)
  }
  tmp <- read.csv( file = f1)
  tmp$Distance <- 0
  tmp$Measure <- 'jaccard'
  tmp$Model <- mdl
  tmp$k <- kVal
  tmp$len <- lenVal	
  # append new data to the result data.frame
  ris <- rbind( ris, tmp)
  cat( sprintf("%s ok\n", f1))
  
  return( ris)
}


models <- c('Uniform', 'Uniform-T1', 'MotifRepl-U', 'PatTransf-U')
dataValues <- c('A', 'B', 'C', 'D', 'N', 'N.D.A')
nPairs = 1000
lengths = c( 200000,600000, 1000000, 5000000, 10000000)
kValues = c(4, 6, 8, 10)
target <- 'inter' # 'N.D.A' # colonna valori di N-D-A

cat('Start loading raw data.\n')

# dataframe risultato
dati <- data.frame( Distance = double(), Measure = character(), Model = character(), k = numeric(), len = numeric(),
                    A = numeric(), B = numeric(), C = numeric(), D = numeric(), N = numeric(), N.D.A = numeric(), stringsAsFactors=TRUE)

for( len in lengths)	{ # 50 lunghezze
  
  for( k in kValues) {  # 4 valori di k
    
    for( model in models) { # 2 AM
      
      if (substr(model, 1, 4) == 'Unif') {
        ret <- ReadResults( model, k, len, 0)
        if (!is.null(ret)) {
          dati <- rbind(dati, ret)
        }
      }
      else {
        for( g in c(0.01, 0.05, 0.10)) {               # 3 valori di gamma
          ret <- ReadResults( model, k, len, g)
          if (!is.null(ret)) {
            dati <- rbind( dati, ret)
          }
        } # for all gamma
      }
    } # for all models
    cat( sprintf("k = %d.  done.\n", k))
  } # for all k
  cat( sprintf("length = %d.  done.\n\n", len))
} # for all length

dati$inter <- with( dati, A / ( N - D))
dati$Model <- factor(dati$Model) # sono già factor
levels(dati$Model) = c('NM', "T1", "MR.G=0.010", "MR.G=0.050", "MR.G=0.100", "PT.G=0.010", "PT.G=0.050", "PT.G=0.100")
####################################
# loading csv raw values terminated.
cat('loading terminated.\n')

####################################

####################################
# start plotting phase
cat('Start plotting.\n')
####################################
for( n in lengths) {

    df <- filter(dati, dati$len == n & dati$Model != 'T1') # solo una misura per tutti i valori di k
    
    if (nrow(df) < 1000) {
      cat( sprintf("Not  enough data (%d) for measure: %s, len: %d\n", nrow(df), target, n))
      stop()
    }
    sp <- ggplot( df, aes(x = Model, y = inter, fill = Model, alpha=0.7)) +
    	geom_boxplot( aes(color = Model), outlier.size = 0.3) +
      # scale_y_continuous(sec.axis = sec_axis(~ . * 10))
    	facet_grid(cols = vars( len), rows = vars( k), scales = "free", labeller = plot_labeller) +
    	# facet_grid_sc(cols = vars( len), rows = vars( k), scales = list( y = scales_y)) +
    	theme_bw() + theme( axis.text.x = element_text(size = 10, angle = 45, hjust = 1)) + # axis.text.y = element_blank()) +
    	theme(legend.position = "none") + labs(x = "") + labs(y = sprintf("Value of A/(N-D)"))
    	# ggtitle(sprintf("Distances for k = %d", kv))
    
    
    # dev.new(width = 16, height = 9)
    outfname <- sprintf("%s-RawValues-len=%d-AllK.pdf", target, n)
    ggsave( outfname, device = pdf(), width = 6, height = 6, dpi = 300)
    # print(sp)
    cat(sprintf("%s processed\n", outfname))
    # dev.off() #only 129kb in size
}