library(DescTools)
library(ggplot2)
library(facetscales)
library(dplyr)
library(stringr)



###### DESCRIPTION

# Given a set of boxplots providing a graphical view of the hamming distance
# of values generated by the Alternative models, with respect to the Null model,
# when considering different values of k and different types of AF measures

# The output is a set of PNG images AFMeasureDistances-All-k=<k>-allMeasures.png, where <k> 
# stands for the actual value of k being considered



###### OPTIONS

# Sets the path of the directory containing the input dataframe

setwd("~/Universita/Src/IdeaProjects/power_statistics/data/results/dataset5-1000")


# Sets the name of the file containing the input dataframe

dfFilename <- "RawDistances-All.RDS"


###### CODE



if (!file.exists(dfFilename)) {
	cat( sprintf("Input Dataframe (%s) does not exist. Exiting\n", dfFilename))
	quit(save = "ask")
}

# carica il dataframe dal file
dati <- readRDS(file = dfFilename)

cat('Start plotting.\n')

# modifica i fattori di scala per ciascuna riga del pannello
# N.B. l'etichetta del pannello deve essere stringa NON numero
scales_y <- list(
    'chebyshev' = scale_y_continuous(limits = c(400, 1300)),
    'd2z' = scale_y_continuous(limits = c(135.80, 136)))

#for labels
len_names <- list(
  '2e+05' = "n = 200 000",
  '5e+06' = "n = 5 000 000")

k_names <- list(
  '4' = "k = 4",
  '6' = "k = 6",
  '8' = "k = 8",
  '10' = "k = 10")

# rename in a human readable format the measure names
measure_names <- function( measure) {
	ris <- c()
  for( m in measure) {
	  ris <- c(ris , str_to_title( switch( m,
			'chisquare' = 'chi\nsquare',
			'd2star' = 'd2*',
			'harmonicmean' = 'harmonic\nmean',
			'squaredchord' = 'squared\nchord',
			'jensenshannon' = 'jensen\nshannon',
			m)))
  }
	return( ris)
}

plot_labeller <- function(variable,value){
	# cat(sprintf("nome: %s, valore: %s\n", variable, as.character(value)))
	if (variable == 'len' || variable == 'k') {
    	return(sprintf("n = %s", formatC( as.integer(value), format = "d", big.mark = " ", digits = 0)))
	} else if (variable == 'Measure') {
		# N.B. Measure e' un factor
	  tr <- measure_names(as.character(value))
	  # cat(sprintf("pre: %s\npost: %s\n", as.character(value), tr))
	  return( tr)
	  # return( as.character(value))
	} else {
		return(as.character(value))
  }
}

for(kv in unique(dati$k)) {

	dff <- filter(dati, dati$len == 5000000 & dati$k == kv & as.character(dati$Model) != "T1") # tutte le misure per uno specifico valore di k senza T1 check
	if (nrow(dff) < 1000) {
		cat( sprintf("Not  enough data (%d) to plot\n", nrow(dff)))
		quit(save = "no")
	}

	sp <- ggplot( dff, aes(x = Model, y = Distance, fill = Model, alpha=0.7)) + 
	 	geom_boxplot( aes(color = Model), outlier.size = 0.3) +
	 	facet_grid(cols = vars( len), rows = vars( Measure), scales = "free", labeller = plot_labeller) +
	 	# facet_grid_sc(cols = vars( len), rows = vars( Measure), scales = list( y = scales_y)) +
	 	# scale_y_continuous(name = "Distance", limits = c(0, 1)) +
	 	theme_bw() + theme( axis.text.x = element_text(size = 9, angle = 45, hjust = 1), axis.text.y = element_blank()) +
	  theme(strip.text = element_text(size=8)) + # face="bold", lineheight=5.0)) +
	 	theme(legend.position = "none") + labs(x = "") + labs(y = "") # Canberra Distances") 
	 	# ggtitle(sprintf("Distances for k = %d", kv)) 
	
	
	# dev.new(width = 4, height = 12)
	outfname <- sprintf("AFMeasureDistances-All-k=%d.png", kv)
	ggsave( outfname, device = png(), width = 6, height = 12, dpi = 300)
	#print(sp)
	cat(sprintf("%s processed\n", outfname))
	# dev.off() #only 129kb in size
}